import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = path.join(root, 'content');
const outputFile = path.join(root, 'src', 'data', 'profile.ts');

async function readJson(fileName) {
  const filePath = path.join(contentDir, fileName);
  try {
    return JSON.parse(await readFile(filePath, 'utf8'));
  } catch (error) {
    throw new Error(`Unable to read ${fileName}: ${error.message}`);
  }
}

function requireString(value, label) {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(`${label} must be a non-empty string`);
  }
  return value.trim();
}

function normalizeProject(project, index) {
  return {
    id: requireString(project.id ?? `project-${index + 1}`, `projects[${index}].id`),
    title: requireString(project.title, `projects[${index}].title`),
    description: requireString(project.description, `projects[${index}].description`),
    highlights: requireString(project.highlights ?? 'Built as part of Akshit Singh portfolio.', `projects[${index}].highlights`),
    tech: Array.isArray(project.tech) ? project.tech.map(String) : [],
    link: typeof project.link === 'string' ? project.link : '#',
    gradient: typeof project.gradient === 'string' ? project.gradient : 'from-cyan-500 to-blue-600'
  };
}

function normalizeExperience(experience, index) {
  return {
    id: requireString(experience.id ?? `experience-${index + 1}`, `experiences[${index}].id`),
    role: requireString(experience.role, `experiences[${index}].role`),
    company: requireString(experience.company, `experiences[${index}].company`),
    period: requireString(experience.period, `experiences[${index}].period`),
    points: Array.isArray(experience.points) ? experience.points.map(String) : [],
    color: typeof experience.color === 'string' ? experience.color : 'cyan'
  };
}

const resume = await readJson('resume.json');
const linkedIn = await readJson('linkedin.json');

const profile = {
  name: requireString(resume.name, 'name'),
  title: requireString(linkedIn.headline ?? resume.title, 'title'),
  badge: requireString(resume.badge, 'badge'),
  summary: requireString(resume.summary, 'summary'),
  email: requireString(resume.email, 'email'),
  phone: requireString(resume.phone, 'phone'),
  location: requireString(resume.location ?? 'India', 'location'),
  links: {
    ...resume.links,
    linkedin: linkedIn.profileUrl ?? resume.links?.linkedin
  },
  stats: Array.isArray(resume.stats) ? resume.stats : [],
  education: resume.education ?? {},
  achievements: Array.isArray(resume.achievements) ? resume.achievements.map(String) : [],
  skills: resume.skills ?? {},
  linkedInSignals: Array.isArray(linkedIn.featuredSignals) ? linkedIn.featuredSignals.map(String) : [],
  experiences: Array.isArray(resume.experiences) ? resume.experiences.map(normalizeExperience) : [],
  projects: Array.isArray(resume.projects) ? resume.projects.map(normalizeProject) : []
};

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(
  outputFile,
  `/* AUTO-GENERATED by scripts/sync-profile.mjs. Edit content/resume.json or content/linkedin.json instead. */\n\nexport const profile = ${JSON.stringify(profile, null, 2)} as const;\n\nexport type Profile = typeof profile;\nexport type Project = Profile['projects'][number];\nexport type Experience = Profile['experiences'][number];\n`,
  'utf8'
);

console.log(`Synced ${profile.projects.length} projects and ${profile.experiences.length} experiences to src/data/profile.ts`);
